# USB interface Makefile. TEST_SRC and TARGET must be set by the caller.

MCU = atmega16u2
ARCH = AVR8
BOARD = UNO
F_CPU = 16000000
F_USB = $(F_CPU)
OPTIMIZATION = s
LUFA_PATH = ../../lufa/LUFA
CC_FLAGS = -DUSE_LUFA_CONFIG_HEADER -I ../usb-iface -Wno-array-bounds
SRC = $(TEST_SRC) ../usb-iface/usb-descriptors.c $(LUFA_SRC_USB)

all:

include $(LUFA_PATH)/Build/lufa_core.mk
include $(LUFA_PATH)/Build/lufa_sources.mk
include $(LUFA_PATH)/Build/lufa_build.mk
